### ISSUE TITLE
Tailwindcss 4.0 support?

### ISSUE THREAD

**Issue by greglearns** [JavierM42/tailwind-material-colors#15]
This project looks super exciting. What's your thoughts or plan for supporting Tailwind 4.0? Many months away? Never? Thanks!

**Comment by JosefJezek** [comment]
Pls, we need support for v4. Thank you.

**Comment by abernier** [comment]
i think the legacy `@plugin` should just work here?

**Comment by abernier** [comment]
for reference https://chatgpt.com/share/68135716-3b34-8011-8ccb-b035bfdbd027

tldr;

- legacy [`@config`](https://tailwindcss.com/docs/functions-and-directives#config-directive) should probably just work:
  ```css
  /* app.css */
  @import "tailwindcss";
  
  @config "./tailwind.config.js"
  ```

- in the meantime of porting to a full tw4 [`@plugin`](https://tailwindcss.com/docs/functions-and-directives#plugin-directive):
  ```css
  /* app.css */
  @import "tailwindcss";
  
  @plugin "material-colors" {
    primary: #123456;
    ...
  }
  ```
  ^ as described in [chatgpt link](https://chatgpt.com/share/68135716-3b34-8011-8ccb-b035bfdbd027)
